begin;

create extension if not exists unaccent;

create table if not exists public.payment_methods (
  code text primary key check (code in ('cod', 'bank_transfer', 'showroom')),
  display_name text not null,
  description text,
  config jsonb not null default '{}'::jsonb check (jsonb_typeof(config) = 'object'),
  is_active boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shipping_zones (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  provinces text[] not null default '{}'::text[],
  base_fee numeric(14, 2) not null check (base_fee >= 0),
  free_shipping_threshold numeric(14, 2) check (free_shipping_threshold is null or free_shipping_threshold >= 0),
  estimated_days_min integer not null default 1 check (estimated_days_min > 0),
  estimated_days_max integer not null default 3 check (estimated_days_max >= estimated_days_min),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_outbox (
  id bigint generated by default as identity primary key,
  event_type text not null,
  channel text not null check (channel in ('internal', 'email', 'sms')),
  recipient text,
  order_id uuid references public.orders(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'processing', 'sent', 'failed', 'cancelled')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error text,
  available_at timestamptz not null default now(),
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists notification_outbox_pending_idx
  on public.notification_outbox (status, available_at, created_at)
  where status in ('pending', 'failed');
create index if not exists notification_outbox_order_idx
  on public.notification_outbox (order_id, created_at desc)
  where order_id is not null;

alter table public.orders
  add column if not exists shipping_zone_id uuid references public.shipping_zones(id) on delete set null,
  add column if not exists payment_reference text;

alter table public.payment_methods enable row level security;
alter table public.shipping_zones enable row level security;
alter table public.notification_outbox enable row level security;

drop policy if exists "payment_methods_public_active_read" on public.payment_methods;
create policy "payment_methods_public_active_read"
  on public.payment_methods for select to anon, authenticated
  using (is_active = true);
drop policy if exists "payment_methods_staff_read" on public.payment_methods;
create policy "payment_methods_staff_read"
  on public.payment_methods for select to authenticated
  using (public.is_staff());

drop policy if exists "shipping_zones_public_active_read" on public.shipping_zones;
create policy "shipping_zones_public_active_read"
  on public.shipping_zones for select to anon, authenticated
  using (is_active = true);
drop policy if exists "shipping_zones_staff_read" on public.shipping_zones;
create policy "shipping_zones_staff_read"
  on public.shipping_zones for select to authenticated
  using (public.is_staff());

drop policy if exists "notification_outbox_staff_read" on public.notification_outbox;
create policy "notification_outbox_staff_read"
  on public.notification_outbox for select to authenticated
  using (public.is_staff());

revoke all on public.payment_methods, public.shipping_zones, public.notification_outbox from anon, authenticated;
grant select on public.payment_methods, public.shipping_zones to anon, authenticated;
grant select on public.notification_outbox to authenticated;

drop trigger if exists payment_methods_set_updated_at on public.payment_methods;
create trigger payment_methods_set_updated_at before update on public.payment_methods
for each row execute function public.set_updated_at();
drop trigger if exists shipping_zones_set_updated_at on public.shipping_zones;
create trigger shipping_zones_set_updated_at before update on public.shipping_zones
for each row execute function public.set_updated_at();
drop trigger if exists notification_outbox_set_updated_at on public.notification_outbox;
create trigger notification_outbox_set_updated_at before update on public.notification_outbox
for each row execute function public.set_updated_at();

insert into public.payment_methods (code, display_name, description, config, is_active, sort_order)
values
  ('cod', 'Thanh toán khi nhận hàng', 'Thanh toán tiền mặt hoặc theo hướng dẫn của nhân viên giao hàng.', '{}'::jsonb, true, 1),
  ('bank_transfer', 'Chuyển khoản ngân hàng', 'Chuyển khoản theo mã đơn hàng sau khi cửa hàng xác nhận.', '{"bank_name":"","bank_bin":"","account_number":"","account_name":"","instructions":"Nội dung chuyển khoản là mã đơn hàng."}'::jsonb, false, 2),
  ('showroom', 'Thanh toán tại showroom', 'Thanh toán và nhận hàng trực tiếp tại showroom.', '{"address":"10 Ngõ 117 Thái Hà, Hà Nội"}'::jsonb, true, 3)
on conflict (code) do update set
  display_name = excluded.display_name,
  description = excluded.description,
  sort_order = excluded.sort_order;

insert into public.shipping_zones (
  code, name, provinces, base_fee, free_shipping_threshold,
  estimated_days_min, estimated_days_max, is_active, sort_order
)
values
  ('hanoi', 'Nội thành Hà Nội', array['Hà Nội', 'Ha Noi'], 30000, 20000000, 1, 2, true, 1),
  ('nationwide', 'Toàn quốc', '{}'::text[], 50000, 30000000, 2, 5, true, 99)
on conflict (code) do update set
  name = excluded.name,
  provinces = excluded.provinces,
  base_fee = excluded.base_fee,
  free_shipping_threshold = excluded.free_shipping_threshold,
  estimated_days_min = excluded.estimated_days_min,
  estimated_days_max = excluded.estimated_days_max,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;

create or replace function public.resolve_shipping_quote(
  p_province text,
  p_subtotal numeric
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_zone public.shipping_zones%rowtype;
  v_fee numeric(14, 2);
begin
  select * into v_zone
  from public.shipping_zones zone
  where zone.is_active = true
    and (
      cardinality(zone.provinces) = 0
      or exists (
        select 1 from unnest(zone.provinces) province
        where lower(unaccent(province)) = lower(unaccent(btrim(coalesce(p_province, ''))))
      )
    )
  order by case when cardinality(zone.provinces) > 0 then 0 else 1 end, zone.sort_order
  limit 1;

  if not found then raise exception 'SHIPPING_ZONE_NOT_FOUND'; end if;
  v_fee := case
    when v_zone.free_shipping_threshold is not null and p_subtotal >= v_zone.free_shipping_threshold then 0
    else v_zone.base_fee
  end;

  return jsonb_build_object(
    'zone_id', v_zone.id,
    'zone_code', v_zone.code,
    'zone_name', v_zone.name,
    'shipping_fee', v_fee,
    'free_shipping_threshold', v_zone.free_shipping_threshold,
    'estimated_days_min', v_zone.estimated_days_min,
    'estimated_days_max', v_zone.estimated_days_max
  );
end;
$$;

revoke all on function public.resolve_shipping_quote(text, numeric) from public;
grant execute on function public.resolve_shipping_quote(text, numeric) to anon, authenticated;

create or replace function public.get_checkout_configuration(
  p_province text,
  p_subtotal numeric
)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'shipping', public.resolve_shipping_quote(p_province, greatest(coalesce(p_subtotal, 0), 0)),
    'payment_methods', coalesce((
      select jsonb_agg(jsonb_build_object(
        'code', code,
        'display_name', display_name,
        'description', description,
        'config', config
      ) order by sort_order)
      from public.payment_methods
      where is_active = true
    ), '[]'::jsonb)
  );
$$;

revoke all on function public.get_checkout_configuration(text, numeric) from public;
grant execute on function public.get_checkout_configuration(text, numeric) to anon, authenticated;

-- Checkout facade: the inventory transaction stays isolated in
-- create_guest_order while this layer applies configurable fulfillment rules.
create or replace function public.create_checkout_order(
  p_customer jsonb,
  p_items jsonb,
  p_payment_method text default 'cod',
  p_notes text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_result jsonb;
  v_order_id uuid;
  v_order public.orders%rowtype;
  v_quote jsonb;
  v_payment_config jsonb;
  v_shipping_fee numeric(14, 2);
  v_total numeric(14, 2);
begin
  select config into v_payment_config
  from public.payment_methods
  where code = p_payment_method and is_active = true;
  if not found then raise exception 'PAYMENT_METHOD_UNAVAILABLE'; end if;

  v_result := public.create_guest_order(p_customer, p_items, p_payment_method, p_notes);
  v_order_id := (v_result->>'order_id')::uuid;
  select * into v_order from public.orders where id = v_order_id for update;
  v_quote := public.resolve_shipping_quote(v_order.shipping_province, v_order.subtotal);
  v_shipping_fee := (v_quote->>'shipping_fee')::numeric;
  v_total := v_order.subtotal - v_order.discount_total + v_shipping_fee;

  update public.orders
  set shipping_zone_id = (v_quote->>'zone_id')::uuid,
      shipping_fee = v_shipping_fee,
      total = v_total,
      payment_reference = v_order.order_code,
      updated_at = now()
  where id = v_order_id;

  insert into public.notification_outbox (event_type, channel, recipient, order_id, payload)
  values (
    'order_created', 'internal', null, v_order_id,
    jsonb_build_object('order_code', v_order.order_code, 'total', v_total)
  );
  if v_order.customer_email is not null then
    insert into public.notification_outbox (event_type, channel, recipient, order_id, payload)
    values (
      'order_created', 'email', v_order.customer_email, v_order_id,
      jsonb_build_object('order_code', v_order.order_code, 'customer_name', v_order.customer_name, 'total', v_total)
    );
  end if;

  return v_result || jsonb_build_object(
    'shipping', v_quote,
    'shipping_fee', v_shipping_fee,
    'total', v_total,
    'payment_reference', v_order.order_code,
    'payment_config', v_payment_config
  );
end;
$$;

revoke all on function public.create_checkout_order(jsonb, jsonb, text, text) from public;
grant execute on function public.create_checkout_order(jsonb, jsonb, text, text) to anon, authenticated;
revoke execute on function public.create_guest_order(jsonb, jsonb, text, text) from anon, authenticated;

create or replace function public.queue_order_status_notification()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders%rowtype;
begin
  select * into v_order from public.orders where id = new.order_id;
  insert into public.notification_outbox (event_type, channel, recipient, order_id, payload)
  values (
    'order_status_changed', 'internal', null, new.order_id,
    jsonb_build_object('order_code', v_order.order_code, 'from_status', new.from_status, 'to_status', new.to_status, 'note', new.note)
  );
  if v_order.customer_email is not null then
    insert into public.notification_outbox (event_type, channel, recipient, order_id, payload)
    values (
      'order_status_changed', 'email', v_order.customer_email, new.order_id,
      jsonb_build_object('order_code', v_order.order_code, 'customer_name', v_order.customer_name, 'from_status', new.from_status, 'to_status', new.to_status)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists order_status_history_queue_notification on public.order_status_history;
create trigger order_status_history_queue_notification
  after insert on public.order_status_history
  for each row execute function public.queue_order_status_notification();

create or replace function public.admin_update_payment_method(
  p_code text,
  p_display_name text,
  p_description text,
  p_config jsonb,
  p_is_active boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_result public.payment_methods%rowtype;
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  if jsonb_typeof(coalesce(p_config, '{}'::jsonb)) <> 'object' then raise exception 'INVALID_CONFIG'; end if;
  update public.payment_methods
  set display_name = btrim(p_display_name),
      description = nullif(btrim(coalesce(p_description, '')), ''),
      config = coalesce(p_config, '{}'::jsonb),
      is_active = p_is_active,
      updated_at = now()
  where code = p_code
  returning * into v_result;
  if not found then raise exception 'PAYMENT_METHOD_NOT_FOUND'; end if;
  return to_jsonb(v_result);
end;
$$;

revoke all on function public.admin_update_payment_method(text, text, text, jsonb, boolean) from public;
grant execute on function public.admin_update_payment_method(text, text, text, jsonb, boolean) to authenticated;

create or replace function public.admin_upsert_shipping_zone(p_zone jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id uuid := nullif(p_zone->>'id', '')::uuid;
  v_result public.shipping_zones%rowtype;
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  if v_id is null then v_id := gen_random_uuid(); end if;
  insert into public.shipping_zones (
    id, code, name, provinces, base_fee, free_shipping_threshold,
    estimated_days_min, estimated_days_max, is_active, sort_order
  ) values (
    v_id,
    btrim(p_zone->>'code'),
    btrim(p_zone->>'name'),
    coalesce(array(select jsonb_array_elements_text(coalesce(p_zone->'provinces', '[]'::jsonb))), '{}'::text[]),
    (p_zone->>'base_fee')::numeric,
    nullif(p_zone->>'free_shipping_threshold', '')::numeric,
    coalesce((p_zone->>'estimated_days_min')::integer, 1),
    coalesce((p_zone->>'estimated_days_max')::integer, 3),
    coalesce((p_zone->>'is_active')::boolean, true),
    coalesce((p_zone->>'sort_order')::integer, 0)
  )
  on conflict (id) do update set
    code = excluded.code,
    name = excluded.name,
    provinces = excluded.provinces,
    base_fee = excluded.base_fee,
    free_shipping_threshold = excluded.free_shipping_threshold,
    estimated_days_min = excluded.estimated_days_min,
    estimated_days_max = excluded.estimated_days_max,
    is_active = excluded.is_active,
    sort_order = excluded.sort_order,
    updated_at = now()
  returning * into v_result;
  return to_jsonb(v_result);
end;
$$;

revoke all on function public.admin_upsert_shipping_zone(jsonb) from public;
grant execute on function public.admin_upsert_shipping_zone(jsonb) to authenticated;

commit;
