begin;

create table if not exists public.product_reviews (
  id uuid primary key default gen_random_uuid(),
  product_id text not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_item_id bigint references public.order_items(id) on delete set null,
  reviewer_name text not null,
  rating integer not null check (rating between 1 and 5),
  title text,
  content text not null,
  status text not null default 'pending' check (status in ('pending', 'published', 'rejected')),
  is_verified_purchase boolean not null default false,
  helpful_count integer not null default 0 check (helpful_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_id)
);
create index if not exists product_reviews_public_idx
  on public.product_reviews (product_id, status, created_at desc);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  discount_type text not null check (discount_type in ('percentage', 'amount')),
  discount_value numeric(14, 2) not null check (discount_value > 0),
  minimum_order_value numeric(14, 2) not null default 0 check (minimum_order_value >= 0),
  maximum_discount numeric(14, 2) check (maximum_discount is null or maximum_discount > 0),
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  used_count integer not null default 0 check (used_count >= 0),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at),
  check (discount_type <> 'percentage' or discount_value <= 100)
);
create index if not exists coupons_active_idx on public.coupons (is_active, starts_at, ends_at);

create table if not exists public.coupon_redemptions (
  id bigint generated by default as identity primary key,
  coupon_id uuid not null references public.coupons(id) on delete restrict,
  order_id uuid not null unique references public.orders(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  discount_amount numeric(14, 2) not null check (discount_amount >= 0),
  created_at timestamptz not null default now()
);
create index if not exists coupon_redemptions_coupon_idx on public.coupon_redemptions (coupon_id, created_at desc);
create index if not exists coupon_redemptions_user_idx on public.coupon_redemptions (user_id, created_at desc) where user_id is not null;

alter table public.orders add column if not exists coupon_code text;

alter table public.product_reviews enable row level security;
alter table public.coupons enable row level security;
alter table public.coupon_redemptions enable row level security;

drop policy if exists "product_reviews_public_read" on public.product_reviews;
create policy "product_reviews_public_read" on public.product_reviews for select to anon, authenticated
using (status = 'published');
drop policy if exists "product_reviews_owner_read" on public.product_reviews;
create policy "product_reviews_owner_read" on public.product_reviews for select to authenticated
using (user_id = auth.uid());
drop policy if exists "product_reviews_staff_read" on public.product_reviews;
create policy "product_reviews_staff_read" on public.product_reviews for select to authenticated
using (public.is_staff());

drop policy if exists "coupons_staff_read" on public.coupons;
create policy "coupons_staff_read" on public.coupons for select to authenticated
using (public.is_staff());
drop policy if exists "coupon_redemptions_staff_read" on public.coupon_redemptions;
create policy "coupon_redemptions_staff_read" on public.coupon_redemptions for select to authenticated
using (public.is_staff());
drop policy if exists "coupon_redemptions_owner_read" on public.coupon_redemptions;
create policy "coupon_redemptions_owner_read" on public.coupon_redemptions for select to authenticated
using (user_id = auth.uid());

revoke all on public.product_reviews, public.coupons, public.coupon_redemptions from anon, authenticated;
grant select on public.product_reviews to anon, authenticated;
grant select on public.coupons, public.coupon_redemptions to authenticated;

drop trigger if exists product_reviews_set_updated_at on public.product_reviews;
create trigger product_reviews_set_updated_at before update on public.product_reviews
for each row execute function public.set_updated_at();
drop trigger if exists coupons_set_updated_at on public.coupons;
create trigger coupons_set_updated_at before update on public.coupons
for each row execute function public.set_updated_at();

create or replace function public.validate_coupon(
  p_code text,
  p_subtotal numeric
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_coupon public.coupons%rowtype;
  v_discount numeric(14, 2);
begin
  select * into v_coupon
  from public.coupons
  where upper(code) = upper(btrim(p_code))
    and is_active = true
    and now() between starts_at and ends_at;
  if not found then raise exception 'COUPON_INVALID'; end if;
  if v_coupon.usage_limit is not null and v_coupon.used_count >= v_coupon.usage_limit then raise exception 'COUPON_EXHAUSTED'; end if;
  if p_subtotal < v_coupon.minimum_order_value then raise exception 'COUPON_MINIMUM_NOT_MET'; end if;

  v_discount := case
    when v_coupon.discount_type = 'percentage' then p_subtotal * v_coupon.discount_value / 100
    else v_coupon.discount_value
  end;
  if v_coupon.maximum_discount is not null then v_discount := least(v_discount, v_coupon.maximum_discount); end if;
  v_discount := greatest(0, least(v_discount, p_subtotal));

  return jsonb_build_object(
    'coupon_id', v_coupon.id,
    'code', v_coupon.code,
    'name', v_coupon.name,
    'description', v_coupon.description,
    'discount_amount', round(v_discount, 2),
    'minimum_order_value', v_coupon.minimum_order_value
  );
end;
$$;

revoke all on function public.validate_coupon(text, numeric) from public;
grant execute on function public.validate_coupon(text, numeric) to anon, authenticated;

create or replace function public.create_checkout_order_v2(
  p_customer jsonb,
  p_items jsonb,
  p_payment_method text default 'cod',
  p_notes text default null,
  p_coupon_code text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_result jsonb;
  v_order_id uuid;
  v_order public.orders%rowtype;
  v_coupon jsonb;
  v_discount numeric(14, 2) := 0;
  v_quote jsonb;
  v_shipping_fee numeric(14, 2);
  v_total numeric(14, 2);
begin
  v_result := public.create_checkout_order(p_customer, p_items, p_payment_method, p_notes);
  v_order_id := (v_result->>'order_id')::uuid;
  select * into v_order from public.orders where id = v_order_id for update;

  if nullif(btrim(coalesce(p_coupon_code, '')), '') is not null then
    v_coupon := public.validate_coupon(p_coupon_code, v_order.subtotal);
    select * into v_order from public.orders where id = v_order_id for update;
    perform 1 from public.coupons where id = (v_coupon->>'coupon_id')::uuid for update;
    -- Revalidate after locking to prevent exceeding the global usage limit.
    v_coupon := public.validate_coupon(p_coupon_code, v_order.subtotal);
    v_discount := (v_coupon->>'discount_amount')::numeric;

    insert into public.coupon_redemptions (coupon_id, order_id, user_id, discount_amount)
    values ((v_coupon->>'coupon_id')::uuid, v_order_id, auth.uid(), v_discount);
    update public.coupons set used_count = used_count + 1, updated_at = now()
    where id = (v_coupon->>'coupon_id')::uuid;
  end if;

  v_quote := public.resolve_shipping_quote(v_order.shipping_province, greatest(v_order.subtotal - v_discount, 0));
  v_shipping_fee := (v_quote->>'shipping_fee')::numeric;
  v_total := greatest(v_order.subtotal - v_discount, 0) + v_shipping_fee;
  update public.orders
  set discount_total = v_discount,
      coupon_code = case when v_coupon is null then null else v_coupon->>'code' end,
      shipping_zone_id = (v_quote->>'zone_id')::uuid,
      shipping_fee = v_shipping_fee,
      total = v_total,
      updated_at = now()
  where id = v_order_id;

  update public.notification_outbox
  set payload = payload || jsonb_build_object('discount_total', v_discount, 'total', v_total), updated_at = now()
  where order_id = v_order_id and event_type = 'order_created' and status = 'pending';

  return v_result || jsonb_build_object(
    'coupon', v_coupon,
    'discount_total', v_discount,
    'shipping', v_quote,
    'shipping_fee', v_shipping_fee,
    'total', v_total
  );
end;
$$;

revoke all on function public.create_checkout_order_v2(jsonb, jsonb, text, text, text) from public;
grant execute on function public.create_checkout_order_v2(jsonb, jsonb, text, text, text) to anon, authenticated;
revoke execute on function public.create_checkout_order(jsonb, jsonb, text, text) from anon, authenticated;

create or replace function public.submit_product_review(
  p_product_id text,
  p_rating integer,
  p_title text,
  p_content text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_item_id bigint;
  v_reviewer_name text;
  v_result public.product_reviews%rowtype;
begin
  if v_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_rating < 1 or p_rating > 5 then raise exception 'INVALID_RATING'; end if;
  if char_length(btrim(coalesce(p_content, ''))) < 10 or char_length(btrim(p_content)) > 2000 then raise exception 'INVALID_REVIEW_CONTENT'; end if;

  select oi.id into v_order_item_id
  from public.order_items oi
  join public.orders o on o.id = oi.order_id
  where o.user_id = v_user_id
    and o.status = 'completed'
    and oi.product_id = p_product_id
  order by o.completed_at desc nulls last, o.created_at desc
  limit 1;
  if not found then raise exception 'VERIFIED_PURCHASE_REQUIRED'; end if;

  select coalesce(nullif(btrim(full_name), ''), 'Khách hàng') into v_reviewer_name
  from public.customer_profiles where user_id = v_user_id;
  v_reviewer_name := coalesce(v_reviewer_name, 'Khách hàng');

  insert into public.product_reviews (
    product_id, user_id, order_item_id, reviewer_name, rating, title, content,
    status, is_verified_purchase
  ) values (
    p_product_id, v_user_id, v_order_item_id, v_reviewer_name, p_rating,
    nullif(btrim(coalesce(p_title, '')), ''), btrim(p_content), 'pending', true
  )
  on conflict (user_id, product_id) do update set
    rating = excluded.rating,
    title = excluded.title,
    content = excluded.content,
    status = 'pending',
    order_item_id = excluded.order_item_id,
    is_verified_purchase = true,
    updated_at = now()
  returning * into v_result;
  return to_jsonb(v_result);
end;
$$;

revoke all on function public.submit_product_review(text, integer, text, text) from public;
grant execute on function public.submit_product_review(text, integer, text, text) to authenticated;

create or replace function public.admin_moderate_review(
  p_review_id uuid,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_result public.product_reviews%rowtype;
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  if p_status not in ('pending', 'published', 'rejected') then raise exception 'INVALID_REVIEW_STATUS'; end if;
  update public.product_reviews set status = p_status, updated_at = now()
  where id = p_review_id returning * into v_result;
  if not found then raise exception 'REVIEW_NOT_FOUND'; end if;
  return to_jsonb(v_result);
end;
$$;

revoke all on function public.admin_moderate_review(uuid, text) from public;
grant execute on function public.admin_moderate_review(uuid, text) to authenticated;

create or replace function public.admin_upsert_coupon(p_coupon jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id uuid := nullif(p_coupon->>'id', '')::uuid;
  v_result public.coupons%rowtype;
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  if v_id is null then v_id := gen_random_uuid(); end if;
  insert into public.coupons (
    id, code, name, description, discount_type, discount_value,
    minimum_order_value, maximum_discount, usage_limit,
    starts_at, ends_at, is_active
  ) values (
    v_id, upper(btrim(p_coupon->>'code')), btrim(p_coupon->>'name'),
    nullif(btrim(coalesce(p_coupon->>'description', '')), ''),
    p_coupon->>'discount_type', (p_coupon->>'discount_value')::numeric,
    coalesce((p_coupon->>'minimum_order_value')::numeric, 0),
    nullif(p_coupon->>'maximum_discount', '')::numeric,
    nullif(p_coupon->>'usage_limit', '')::integer,
    (p_coupon->>'starts_at')::timestamptz,
    (p_coupon->>'ends_at')::timestamptz,
    coalesce((p_coupon->>'is_active')::boolean, true)
  )
  on conflict (id) do update set
    code = excluded.code,
    name = excluded.name,
    description = excluded.description,
    discount_type = excluded.discount_type,
    discount_value = excluded.discount_value,
    minimum_order_value = excluded.minimum_order_value,
    maximum_discount = excluded.maximum_discount,
    usage_limit = excluded.usage_limit,
    starts_at = excluded.starts_at,
    ends_at = excluded.ends_at,
    is_active = excluded.is_active,
    updated_at = now()
  returning * into v_result;
  return to_jsonb(v_result);
end;
$$;

revoke all on function public.admin_upsert_coupon(jsonb) from public;
grant execute on function public.admin_upsert_coupon(jsonb) to authenticated;

commit;

