begin;

-- Staff identity and operational audit trail.
create table if not exists public.staff_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'staff')),
  display_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete restrict,
  order_id uuid references public.orders(id) on delete set null,
  movement_type text not null check (movement_type in ('initial', 'sale', 'restock', 'correction', 'cancellation')),
  quantity_delta integer,
  stock_after integer,
  note text,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists inventory_movements_product_idx
  on public.inventory_movements (product_id, created_at desc);
create index if not exists inventory_movements_order_idx
  on public.inventory_movements (order_id)
  where order_id is not null;

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  from_status text,
  to_status text not null,
  note text,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists order_status_history_order_idx
  on public.order_status_history (order_id, created_at desc);

alter table public.orders
  add column if not exists inventory_committed boolean not null default false,
  add column if not exists sales_committed boolean not null default false,
  add column if not exists cancelled_at timestamptz,
  add column if not exists completed_at timestamptz;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.staff_members
    where user_id = auth.uid()
      and is_active = true
      and role in ('admin', 'staff')
  );
$$;

revoke all on function public.is_staff() from public;
grant execute on function public.is_staff() to authenticated;

alter table public.staff_members enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.order_status_history enable row level security;
alter table public.products enable row level security;

drop policy if exists "staff_members_read_own_or_staff" on public.staff_members;
create policy "staff_members_read_own_or_staff"
  on public.staff_members for select to authenticated
  using (user_id = auth.uid() or public.is_staff());

drop policy if exists "inventory_movements_staff_read" on public.inventory_movements;
create policy "inventory_movements_staff_read"
  on public.inventory_movements for select to authenticated
  using (public.is_staff());

drop policy if exists "order_status_history_staff_read" on public.order_status_history;
create policy "order_status_history_staff_read"
  on public.order_status_history for select to authenticated
  using (public.is_staff());

drop policy if exists "order_status_history_owner_read" on public.order_status_history;
create policy "order_status_history_owner_read"
  on public.order_status_history for select to authenticated
  using (exists (
    select 1 from public.orders
    where orders.id = order_status_history.order_id
      and orders.user_id = auth.uid()
  ));

-- Replace any legacy broad product-read policy so drafts cannot leak publicly.
do $$
declare
  v_policy record;
begin
  for v_policy in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'products'
      and cmd = 'SELECT'
  loop
    execute format('drop policy if exists %I on public.products', v_policy.policyname);
  end loop;
end $$;

create policy "products_public_active_read"
  on public.products for select to anon, authenticated
  using (status = 'active');

drop policy if exists "products_staff_read" on public.products;
create policy "products_staff_read"
  on public.products for select to authenticated
  using (public.is_staff());

drop policy if exists "orders_staff_read" on public.orders;
create policy "orders_staff_read"
  on public.orders for select to authenticated
  using (public.is_staff());

drop policy if exists "order_items_staff_read" on public.order_items;
create policy "order_items_staff_read"
  on public.order_items for select to authenticated
  using (public.is_staff());

revoke all on public.staff_members, public.inventory_movements, public.order_status_history from anon, authenticated;
grant select on public.staff_members, public.inventory_movements, public.order_status_history to authenticated;
grant select on public.products to anon, authenticated;

drop trigger if exists staff_members_set_updated_at on public.staff_members;
create trigger staff_members_set_updated_at
  before update on public.staff_members
  for each row execute function public.set_updated_at();

-- Central product mutation contract. The browser never receives service-role credentials.
create or replace function public.admin_upsert_product(p_product jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id text := nullif(btrim(coalesce(p_product->>'id', '')), '');
  v_name text := btrim(coalesce(p_product->>'name', ''));
  v_category_id text := btrim(coalesce(p_product->>'category_id', ''));
  v_status text := coalesce(nullif(btrim(p_product->>'status'), ''), 'draft');
  v_price numeric(14, 2);
  v_original_price numeric(14, 2);
  v_discount numeric(6, 2);
  v_stock integer;
  v_specifications jsonb := coalesce(p_product->'specifications', '{}'::jsonb);
  v_previous public.products%rowtype;
  v_result public.products%rowtype;
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  if char_length(v_name) < 2 or char_length(v_name) > 240 then raise exception 'INVALID_PRODUCT_NAME'; end if;
  if v_category_id = '' then raise exception 'INVALID_CATEGORY'; end if;
  if v_status not in ('draft', 'active', 'inactive', 'discontinued') then raise exception 'INVALID_STATUS'; end if;
  if jsonb_typeof(v_specifications) <> 'object' then raise exception 'INVALID_SPECIFICATIONS'; end if;

  begin
    v_price := (p_product->>'price')::numeric;
    v_original_price := coalesce(nullif(p_product->>'original_price', '')::numeric, v_price);
    v_discount := coalesce(nullif(p_product->>'discount', '')::numeric, 0);
    v_stock := case
      when not (p_product ? 'stock_quantity') or p_product->'stock_quantity' = 'null'::jsonb then null
      else (p_product->>'stock_quantity')::integer
    end;
  exception when invalid_text_representation then
    raise exception 'INVALID_PRODUCT_NUMBERS';
  end;

  if v_price <= 0 or v_original_price < v_price then raise exception 'INVALID_PRODUCT_PRICE'; end if;
  if v_discount < 0 or v_discount > 100 then raise exception 'INVALID_DISCOUNT'; end if;
  if v_stock is not null and v_stock < 0 then raise exception 'INVALID_STOCK'; end if;

  if v_id is null then
    v_id := 'product-' || replace(gen_random_uuid()::text, '-', '');
  else
    select * into v_previous from public.products where id = v_id for update;
  end if;

  insert into public.products (
    id, name, price, original_price, discount, category_id, image_url,
    spec_cpu, spec_ram, spec_storage, spec_gpu,
    is_hot, is_flash_sale, is_best_seller, is_new,
    sort_order, sku, brand, status, stock_quantity, specifications
  ) values (
    v_id, v_name, v_price, v_original_price, v_discount, v_category_id,
    nullif(btrim(coalesce(p_product->>'image_url', '')), ''),
    nullif(btrim(coalesce(p_product->>'spec_cpu', '')), ''),
    nullif(btrim(coalesce(p_product->>'spec_ram', '')), ''),
    nullif(btrim(coalesce(p_product->>'spec_storage', '')), ''),
    nullif(btrim(coalesce(p_product->>'spec_gpu', '')), ''),
    coalesce((p_product->>'is_hot')::boolean, false),
    coalesce((p_product->>'is_flash_sale')::boolean, false),
    coalesce((p_product->>'is_best_seller')::boolean, false),
    coalesce((p_product->>'is_new')::boolean, false),
    coalesce(nullif(p_product->>'sort_order', '')::integer, 0),
    nullif(btrim(coalesce(p_product->>'sku', '')), ''),
    nullif(btrim(coalesce(p_product->>'brand', '')), ''),
    v_status, v_stock, v_specifications
  )
  on conflict (id) do update set
    name = excluded.name,
    price = excluded.price,
    original_price = excluded.original_price,
    discount = excluded.discount,
    category_id = excluded.category_id,
    image_url = excluded.image_url,
    spec_cpu = excluded.spec_cpu,
    spec_ram = excluded.spec_ram,
    spec_storage = excluded.spec_storage,
    spec_gpu = excluded.spec_gpu,
    is_hot = excluded.is_hot,
    is_flash_sale = excluded.is_flash_sale,
    is_best_seller = excluded.is_best_seller,
    is_new = excluded.is_new,
    sort_order = excluded.sort_order,
    sku = excluded.sku,
    brand = excluded.brand,
    status = excluded.status,
    stock_quantity = excluded.stock_quantity,
    specifications = excluded.specifications,
    updated_at = now()
  returning * into v_result;

  if v_previous.id is null or v_previous.stock_quantity is distinct from v_result.stock_quantity then
    insert into public.inventory_movements (
      product_id, movement_type, quantity_delta, stock_after, note, actor_user_id
    ) values (
      v_result.id,
      case when v_previous.id is null then 'initial' else 'correction' end,
      case
        when v_result.stock_quantity is null then null
        else v_result.stock_quantity - coalesce(v_previous.stock_quantity, 0)
      end,
      v_result.stock_quantity,
      case when v_previous.id is null then 'Khởi tạo sản phẩm' else 'Cập nhật từ trang quản trị' end,
      auth.uid()
    );
  end if;

  return to_jsonb(v_result);
end;
$$;

revoke all on function public.admin_upsert_product(jsonb) from public;
grant execute on function public.admin_upsert_product(jsonb) to authenticated;

create or replace function public.admin_adjust_inventory(
  p_product_id text,
  p_stock_quantity integer,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_before integer;
  v_result public.products%rowtype;
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  if p_stock_quantity is not null and p_stock_quantity < 0 then raise exception 'INVALID_STOCK'; end if;

  select stock_quantity into v_before
  from public.products
  where id = p_product_id
  for update;
  if not found then raise exception 'PRODUCT_NOT_FOUND'; end if;

  update public.products
  set stock_quantity = p_stock_quantity, updated_at = now()
  where id = p_product_id
  returning * into v_result;

  insert into public.inventory_movements (
    product_id, movement_type, quantity_delta, stock_after, note, actor_user_id
  ) values (
    p_product_id, 'correction',
    case when p_stock_quantity is null then null else p_stock_quantity - coalesce(v_before, 0) end,
    p_stock_quantity, nullif(btrim(coalesce(p_note, '')), ''), auth.uid()
  );

  return to_jsonb(v_result);
end;
$$;

revoke all on function public.admin_adjust_inventory(text, integer, text) from public;
grant execute on function public.admin_adjust_inventory(text, integer, text) to authenticated;

-- Replace guest checkout with an inventory-reserving transaction.
create or replace function public.create_guest_order(
  p_customer jsonb,
  p_items jsonb,
  p_payment_method text default 'cod',
  p_notes text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order_id uuid;
  v_order_code text;
  v_item jsonb;
  v_product public.products%rowtype;
  v_product_id text;
  v_quantity integer;
  v_stock_after integer;
  v_inventory_committed boolean := false;
  v_subtotal numeric(14, 2) := 0;
  v_shipping_fee numeric(14, 2) := 0;
  v_total numeric(14, 2) := 0;
  v_name text := btrim(coalesce(p_customer->>'full_name', ''));
  v_phone text := btrim(coalesce(p_customer->>'phone', ''));
  v_email text := nullif(btrim(coalesce(p_customer->>'email', '')), '');
  v_address text := btrim(coalesce(p_customer->>'address', ''));
  v_province text := btrim(coalesce(p_customer->>'province', ''));
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 30 then
    raise exception 'INVALID_CART';
  end if;
  if char_length(v_name) < 2 or char_length(v_name) > 120 then raise exception 'INVALID_CUSTOMER_NAME'; end if;
  if v_phone !~ '^[0-9+ .-]{8,15}$' then raise exception 'INVALID_PHONE'; end if;
  if char_length(v_address) < 5 or char_length(v_address) > 300 then raise exception 'INVALID_ADDRESS'; end if;
  if char_length(v_province) < 2 or char_length(v_province) > 100 then raise exception 'INVALID_PROVINCE'; end if;
  if p_payment_method not in ('cod', 'bank_transfer', 'showroom') then raise exception 'INVALID_PAYMENT_METHOD'; end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := btrim(coalesce(v_item->>'product_id', ''));
    if v_product_id = '' or coalesce(v_item->>'quantity', '') !~ '^[0-9]+$' then raise exception 'INVALID_CART_ITEM'; end if;
    v_quantity := (v_item->>'quantity')::integer;
    if v_quantity < 1 or v_quantity > 10 then raise exception 'INVALID_QUANTITY'; end if;
  end loop;

  v_order_code := 'LW' || to_char(clock_timestamp(), 'YYMMDD') || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
  insert into public.orders (
    order_code, user_id, customer_name, customer_phone, customer_email,
    shipping_address, shipping_province, payment_method, notes
  ) values (
    v_order_code, auth.uid(), v_name, v_phone, v_email,
    v_address, v_province, p_payment_method, nullif(btrim(coalesce(p_notes, '')), '')
  ) returning id into v_order_id;

  for v_item in
    select jsonb_build_object('product_id', product_id, 'quantity', sum(quantity))
    from (
      select btrim(value->>'product_id') as product_id, (value->>'quantity')::integer as quantity
      from jsonb_array_elements(p_items)
    ) normalized_items
    group by product_id
  loop
    v_product_id := v_item->>'product_id';
    v_quantity := (v_item->>'quantity')::integer;
    if v_quantity > 10 then raise exception 'INVALID_AGGREGATED_QUANTITY'; end if;

    select * into v_product
    from public.products
    where id = v_product_id
    for update;
    if not found or v_product.status <> 'active' then raise exception 'PRODUCT_UNAVAILABLE: %', v_product_id; end if;
    if v_product.price is null or v_product.price <= 0 then raise exception 'INVALID_PRODUCT_PRICE: %', v_product_id; end if;
    if v_product.stock_quantity is not null and v_product.stock_quantity < v_quantity then raise exception 'INSUFFICIENT_STOCK: %', v_product_id; end if;

    if v_product.stock_quantity is not null then
      update public.products
      set stock_quantity = stock_quantity - v_quantity, updated_at = now()
      where id = v_product.id
      returning stock_quantity into v_stock_after;
      v_inventory_committed := true;
      insert into public.inventory_movements (
        product_id, order_id, movement_type, quantity_delta, stock_after, note, actor_user_id
      ) values (
        v_product.id, v_order_id, 'sale', -v_quantity, v_stock_after,
        'Giữ tồn kho khi tạo đơn ' || v_order_code, auth.uid()
      );
    end if;

    insert into public.order_items (
      order_id, product_id, product_name, product_image, unit_price, quantity, product_snapshot
    ) values (
      v_order_id, v_product.id, v_product.name, v_product.image_url, v_product.price, v_quantity,
      jsonb_build_object(
        'sku', v_product.sku,
        'brand', v_product.brand,
        'specifications', v_product.specifications,
        'stock_managed', v_product.stock_quantity is not null
      )
    );
    v_subtotal := v_subtotal + (v_product.price * v_quantity);
  end loop;

  v_shipping_fee := case when v_subtotal >= 20000000 then 0 else 30000 end;
  v_total := v_subtotal + v_shipping_fee;
  update public.orders
  set subtotal = v_subtotal,
      shipping_fee = v_shipping_fee,
      total = v_total,
      inventory_committed = v_inventory_committed
  where id = v_order_id;

  insert into public.order_status_history (order_id, from_status, to_status, note, changed_by)
  values (v_order_id, null, 'pending', 'Đơn hàng được tạo', auth.uid());

  return jsonb_build_object(
    'order_id', v_order_id,
    'order_code', v_order_code,
    'subtotal', v_subtotal,
    'shipping_fee', v_shipping_fee,
    'total', v_total,
    'status', 'pending'
  );
end;
$$;

revoke all on function public.create_guest_order(jsonb, jsonb, text, text) from public;
grant execute on function public.create_guest_order(jsonb, jsonb, text, text) to anon, authenticated;

create or replace function public.admin_update_order(
  p_order_id uuid,
  p_status text,
  p_payment_status text,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order public.orders%rowtype;
  v_item public.order_items%rowtype;
  v_stock_after integer;
  v_previous_status text;
  v_note text := nullif(btrim(coalesce(p_note, '')), '');
begin
  if not public.is_staff() then raise exception 'FORBIDDEN'; end if;
  if p_status not in ('pending', 'confirmed', 'processing', 'shipping', 'completed', 'cancelled') then raise exception 'INVALID_ORDER_STATUS'; end if;
  if p_payment_status not in ('unpaid', 'pending', 'paid', 'refunded') then raise exception 'INVALID_PAYMENT_STATUS'; end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  v_previous_status := v_order.status;

  if p_status <> v_order.status and not (
    (v_order.status = 'pending' and p_status in ('confirmed', 'cancelled')) or
    (v_order.status = 'confirmed' and p_status in ('processing', 'cancelled')) or
    (v_order.status = 'processing' and p_status in ('shipping', 'cancelled')) or
    (v_order.status = 'shipping' and p_status in ('completed', 'cancelled'))
  ) then
    raise exception 'INVALID_STATUS_TRANSITION: % -> %', v_order.status, p_status;
  end if;

  if p_status = 'cancelled' and v_order.status <> 'cancelled' and v_order.inventory_committed then
    for v_item in select * from public.order_items where order_id = v_order.id
    loop
      if coalesce((v_item.product_snapshot->>'stock_managed')::boolean, false) then
        update public.products
        set stock_quantity = stock_quantity + v_item.quantity, updated_at = now()
        where id = v_item.product_id and stock_quantity is not null
        returning stock_quantity into v_stock_after;
        if found then
          insert into public.inventory_movements (
            product_id, order_id, movement_type, quantity_delta, stock_after, note, actor_user_id
          ) values (
            v_item.product_id, v_order.id, 'cancellation', v_item.quantity, v_stock_after,
            coalesce(v_note, 'Hoàn tồn do hủy đơn ' || v_order.order_code), auth.uid()
          );
        end if;
      end if;
    end loop;
  end if;

  if p_status = 'completed' and not v_order.sales_committed then
    for v_item in select * from public.order_items where order_id = v_order.id
    loop
      update public.products
      set sold_count = sold_count + v_item.quantity, updated_at = now()
      where id = v_item.product_id;
    end loop;
  end if;

  update public.orders
  set status = p_status,
      payment_status = p_payment_status,
      inventory_committed = case when p_status = 'cancelled' then false else inventory_committed end,
      sales_committed = case when p_status = 'completed' then true else sales_committed end,
      cancelled_at = case when p_status = 'cancelled' then coalesce(cancelled_at, now()) else cancelled_at end,
      completed_at = case when p_status = 'completed' then coalesce(completed_at, now()) else completed_at end,
      updated_at = now()
  where id = p_order_id
  returning * into v_order;

  insert into public.order_status_history (order_id, from_status, to_status, note, changed_by)
  values (p_order_id, v_previous_status, p_status, v_note, auth.uid());

  return to_jsonb(v_order);
end;
$$;

revoke all on function public.admin_update_order(uuid, text, text, text) from public;
grant execute on function public.admin_update_order(uuid, text, text, text) to authenticated;

commit;

-- Bootstrap the first administrator once in the SQL editor, replacing the email:
-- insert into public.staff_members (user_id, role, display_name)
-- select id, 'admin', coalesce(raw_user_meta_data->>'full_name', email)
-- from auth.users where email = 'admin@example.com'
-- on conflict (user_id) do update set role = 'admin', is_active = true;
